# Generated by Django 3.2.8 on 2021-10-21 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20211020_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercoffee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderers',
            name='order_coffee',
        ),
        migrations.AddField(
            model_name='orderers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertopping',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.ordercoffee'),
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordercoffee',
            name='carts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.carts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderers',
            name='carts',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.carts'),
            preserve_default=False,
        ),
    ]
