# Generated by Django 3.2.8 on 2021-10-27 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoffee',
            name='carts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='newapp.carts'),
        ),
        migrations.AlterField(
            model_name='ordercoffee',
            name='coffee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.coffee'),
        ),
        migrations.AlterField(
            model_name='orderers',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='メールアドレス'),
        ),
    ]
