# Generated by Django 3.2.8 on 2021-10-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_auto_20211027_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertopping',
            name='topping_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.topping'),
        ),
    ]
